# Generated by Django 5.0.6 on 2024-07-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancymodel',
            name='data_updated',
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='experience_id',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='experience_name',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='area_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
