# Generated by Django 5.0.6 on 2024-07-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_vacancymodel_salary_gross'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancymodel',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
