# Generated by Django 5.0.6 on 2024-07-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_vacancymodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancymodel',
            name='alternate_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='salary_max',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='salary_min',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
