# Generated by Django 5.0.6 on 2024-07-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_vacancymodel_alternate_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancymodel',
            name='address_raw',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='employemnt_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='employment_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='has_test',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='schedule_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='schedule_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='snippet_requirement',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='snippet_responsibility',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='type_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='type_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='salary_gross',
            field=models.BooleanField(null=True),
        ),
    ]
