# Generated by Django 5.0.6 on 2024-07-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_vacancymodel_address_raw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancymodel',
            old_name='employemnt_name',
            new_name='employment_name',
        ),
    ]
